### ISSUE TITLE
Error installing this plugin with logstash 7.10.2 docker image

### ISSUE THREAD

**Issue by violalyu** [logstash-plugins/logstash-input-google_pubsub#51]
Hi,

I'm getting this error when trying to install `logstash-input-google_pubsub` to logstash 7.10.2, here's the error:

```
wanqideMacBook-Pro:OTelPlayground wanqilyu$ docker run --rm -it -v ~/projects/OTelPlayground/src/docker/elastic/test.conf:/usr/share/logstash/pipeline/test.conf -v ~/projects/OTelPlayground/otel-test-467bb27f9acd.json:/usr/share/otel-test.json docker.elastic.co/logstash/logstash:7.10.2 sh -c "logstash-plugin install logstash-input-google_pubsub ; /usr/local/bin/docker-entrypoint" -f /usr/share/logstash/pipeline/test.conf
Using bundled JDK: /usr/share/logstash/jdk
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.ext.openssl.SecurityHelper (file:/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/jopenssl.jar) to field java.security.MessageDigest.provider
WARNING: Please consider reporting this to the maintainers of org.jruby.ext.openssl.SecurityHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Validating logstash-input-google_pubsub
Installing logstash-input-google_pubsub
^C^C^C^CError Bundler::InstallError, retrying 1/10
NoMethodError: undefined method `call' for "DEFAULT":String
An error occurred while installing logstash-input-google_pubsub (1.2.1), and Bundler cannot continue.
Make sure that `gem install logstash-input-google_pubsub -v '1.2.1' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  logstash-input-google_pubsub
^CERROR: Installation Aborted, message: undefined method `call' for "DEFAULT":String
```

I tried the same with logstash 6.8.13 and the installation was successful;
Since elastic cloud hosted elasticsearch doesn't work with 6.8.13 for output, I can't use 6.8.13 for my use case.

Any help is appreciated!
